### ISSUE TITLE
Epic: Logged in user can book,update,delete there departures

### ISSUE THREAD

**Issue by Jxkeorton** [Jxkeorton/book-a-skydive#13]
This epic includes all user stories relevant to 

**User stories**
- [x] #2 Experienced skydiver can book a plane - Must have
- [x] #3 Experienced skydiver can delete a booking - Should have
- [x] #9 Experienced skydiver can edit booking - Could have
- [x] #34 
- [x] #33 
- [x] #32 
- [x] #31
